name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}
description: |
    ${project.description}
api-version: 1.13
authors: [puppy3276]
depend: [Vault]
commands:
   color:
     description: Change your name color
     aliases: [colour, col]
     permission: names.color
     usage: /<command> (player)